spring:
  profiles:
    active: dev

  application:
    name: backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backendDB
    username: sa
    password: example

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true   # Set to false if you want to disable Liquibase for certain environments