name: Build and Push Backend Image

on:
  push:
    branches: [develop]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: |
        cd backend
        ./mvnw clean package -DskipTests

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest version and bump
      id: versioning
      run: |
        latest_tag=$(git tag --sort=-v:refname | grep '^v' | head -n 1)
        echo "Latest tag: $latest_tag"
        if [[ -z "$latest_tag" ]]; then latest_tag="v0.0.0"; fi
        IFS='.' read -ra parts <<< "${latest_tag#v}"
        patch=$((parts[2] + 1))
        new_tag="v${parts[0]}.${parts[1]}.$patch"
        echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        docker build -t joshuakudo/ems-backend:${{ steps.versioning.outputs.new_tag }} .
        docker push joshuakudo/ems-backend:${{ steps.versioning.outputs.new_tag }}

    - name: Push Git tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag ${{ steps.versioning.outputs.new_tag }}
        git push origin ${{ steps.versioning.outputs.new_tag }}